[package]
name = "eth_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = "0.24"
hex = "0.4"
rlp = "0.4"
ethers = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
sha3 = "0.10"
rand = "0.8"
